package utils

const (
	E_not_found                = "not_found"
	E_voucher_expired          = "voucher_expired"
	E_voucher_not_active       = "voucher_not_active"
	E_voucher_not_existed      = "voucher_not_existed"
	E_total_bill_not_enough    = "total_bill_not_enough"
	E_code_not_existed         = "code_not_existed"
	E_code_state_invalid       = "code_state_invalid"
	E_not_found_voucher_id     = "not_found_voucher_id"
	E_internal_error           = "internal errors"
	E_not_found_id             = "not_found_id"
	E_invalid_state            = "invalid_state"
	E_can_not_insert_voucher   = "can_not_insert_voucher"
	E_can_not_update_voucher   = "can_not_update_voucher"
	E_can_not_delete_voucher   = "can_not_delete_voucher"
	E_not_found_voucher        = "not_found_voucher"
	E_invalid_discount         = "invalid_discount"
	E_can_not_insert_code      = "can_not_insert_code"
	E_can_not_update_code      = "can_not_update_code"
	E_can_not_delete_code      = "can_not_delete_code"
	E_can_not_insert           = "can_not_insert"
	E_can_not_update           = "can_not_update"
	E_can_not_delete           = "can_not_delete"
	E_voucher_id_empty         = "voucher_id_empty"
	E_name_voucher_empty       = "name_voucher_empty"
	E_point_exchange_empty     = "point_exchange_empty"
	E_total_quantity_empty     = "total_quantity_empty"
	E_start_at_empty           = "start_at_empty"
	E_end_at_empty             = "end_at_empty"
	E_start_at_end_at_invalid  = "start_at_end_at_invalid"
	E_end_at_in_the_past       = "end_at_in_the_past"
	E_voucher_quantity_is_out  = "voucher_quantity_is_out"
	E_voucher_already_redeemed = "voucher_already_redeemed"
)
